/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VocabListRouteImport } from './routes/vocab-list'
import { Route as ShareRouteImport } from './routes/share'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ReleaseNotesRouteImport } from './routes/release-notes'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as KanjiListRouteImport } from './routes/kanji-list'
import { Route as KanaWriteQuizRouteImport } from './routes/kana-write-quiz'
import { Route as KanaWriteRouteImport } from './routes/kana-write'
import { Route as KanaReferenceRouteImport } from './routes/kana-reference'
import { Route as KanaQuizRouteImport } from './routes/kana-quiz'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DrawSearchRouteImport } from './routes/draw-search'
import { Route as DrawRouteImport } from './routes/draw'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VocabWordRouteImport } from './routes/vocab.$word'
import { Route as KanjiCharRouteImport } from './routes/kanji.$char'
import { Route as KanaCharRouteImport } from './routes/kana.$char'

const VocabListRoute = VocabListRouteImport.update({
  id: '/vocab-list',
  path: '/vocab-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleaseNotesRoute = ReleaseNotesRouteImport.update({
  id: '/release-notes',
  path: '/release-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const KanjiListRoute = KanjiListRouteImport.update({
  id: '/kanji-list',
  path: '/kanji-list',
  getParentRoute: () => rootRouteImport,
} as any)
const KanaWriteQuizRoute = KanaWriteQuizRouteImport.update({
  id: '/kana-write-quiz',
  path: '/kana-write-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const KanaWriteRoute = KanaWriteRouteImport.update({
  id: '/kana-write',
  path: '/kana-write',
  getParentRoute: () => rootRouteImport,
} as any)
const KanaReferenceRoute = KanaReferenceRouteImport.update({
  id: '/kana-reference',
  path: '/kana-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const KanaQuizRoute = KanaQuizRouteImport.update({
  id: '/kana-quiz',
  path: '/kana-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawSearchRoute = DrawSearchRouteImport.update({
  id: '/draw-search',
  path: '/draw-search',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawRoute = DrawRouteImport.update({
  id: '/draw',
  path: '/draw',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabWordRoute = VocabWordRouteImport.update({
  id: '/vocab/$word',
  path: '/vocab/$word',
  getParentRoute: () => rootRouteImport,
} as any)
const KanjiCharRoute = KanjiCharRouteImport.update({
  id: '/kanji/$char',
  path: '/kanji/$char',
  getParentRoute: () => rootRouteImport,
} as any)
const KanaCharRoute = KanaCharRouteImport.update({
  id: '/kana/$char',
  path: '/kana/$char',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/credits': typeof CreditsRoute
  '/draw': typeof DrawRoute
  '/draw-search': typeof DrawSearchRoute
  '/history': typeof HistoryRoute
  '/kana-quiz': typeof KanaQuizRoute
  '/kana-reference': typeof KanaReferenceRoute
  '/kana-write': typeof KanaWriteRoute
  '/kana-write-quiz': typeof KanaWriteQuizRoute
  '/kanji-list': typeof KanjiListRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/release-notes': typeof ReleaseNotesRoute
  '/review': typeof ReviewRoute
  '/share': typeof ShareRoute
  '/vocab-list': typeof VocabListRoute
  '/kana/$char': typeof KanaCharRoute
  '/kanji/$char': typeof KanjiCharRoute
  '/vocab/$word': typeof VocabWordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/credits': typeof CreditsRoute
  '/draw': typeof DrawRoute
  '/draw-search': typeof DrawSearchRoute
  '/history': typeof HistoryRoute
  '/kana-quiz': typeof KanaQuizRoute
  '/kana-reference': typeof KanaReferenceRoute
  '/kana-write': typeof KanaWriteRoute
  '/kana-write-quiz': typeof KanaWriteQuizRoute
  '/kanji-list': typeof KanjiListRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/release-notes': typeof ReleaseNotesRoute
  '/review': typeof ReviewRoute
  '/share': typeof ShareRoute
  '/vocab-list': typeof VocabListRoute
  '/kana/$char': typeof KanaCharRoute
  '/kanji/$char': typeof KanjiCharRoute
  '/vocab/$word': typeof VocabWordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/credits': typeof CreditsRoute
  '/draw': typeof DrawRoute
  '/draw-search': typeof DrawSearchRoute
  '/history': typeof HistoryRoute
  '/kana-quiz': typeof KanaQuizRoute
  '/kana-reference': typeof KanaReferenceRoute
  '/kana-write': typeof KanaWriteRoute
  '/kana-write-quiz': typeof KanaWriteQuizRoute
  '/kanji-list': typeof KanjiListRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/release-notes': typeof ReleaseNotesRoute
  '/review': typeof ReviewRoute
  '/share': typeof ShareRoute
  '/vocab-list': typeof VocabListRoute
  '/kana/$char': typeof KanaCharRoute
  '/kanji/$char': typeof KanjiCharRoute
  '/vocab/$word': typeof VocabWordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/credits'
    | '/draw'
    | '/draw-search'
    | '/history'
    | '/kana-quiz'
    | '/kana-reference'
    | '/kana-write'
    | '/kana-write-quiz'
    | '/kanji-list'
    | '/profile'
    | '/quiz'
    | '/release-notes'
    | '/review'
    | '/share'
    | '/vocab-list'
    | '/kana/$char'
    | '/kanji/$char'
    | '/vocab/$word'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/credits'
    | '/draw'
    | '/draw-search'
    | '/history'
    | '/kana-quiz'
    | '/kana-reference'
    | '/kana-write'
    | '/kana-write-quiz'
    | '/kanji-list'
    | '/profile'
    | '/quiz'
    | '/release-notes'
    | '/review'
    | '/share'
    | '/vocab-list'
    | '/kana/$char'
    | '/kanji/$char'
    | '/vocab/$word'
  id:
    | '__root__'
    | '/'
    | '/credits'
    | '/draw'
    | '/draw-search'
    | '/history'
    | '/kana-quiz'
    | '/kana-reference'
    | '/kana-write'
    | '/kana-write-quiz'
    | '/kanji-list'
    | '/profile'
    | '/quiz'
    | '/release-notes'
    | '/review'
    | '/share'
    | '/vocab-list'
    | '/kana/$char'
    | '/kanji/$char'
    | '/vocab/$word'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreditsRoute: typeof CreditsRoute
  DrawRoute: typeof DrawRoute
  DrawSearchRoute: typeof DrawSearchRoute
  HistoryRoute: typeof HistoryRoute
  KanaQuizRoute: typeof KanaQuizRoute
  KanaReferenceRoute: typeof KanaReferenceRoute
  KanaWriteRoute: typeof KanaWriteRoute
  KanaWriteQuizRoute: typeof KanaWriteQuizRoute
  KanjiListRoute: typeof KanjiListRoute
  ProfileRoute: typeof ProfileRoute
  QuizRoute: typeof QuizRoute
  ReleaseNotesRoute: typeof ReleaseNotesRoute
  ReviewRoute: typeof ReviewRoute
  ShareRoute: typeof ShareRoute
  VocabListRoute: typeof VocabListRoute
  KanaCharRoute: typeof KanaCharRoute
  KanjiCharRoute: typeof KanjiCharRoute
  VocabWordRoute: typeof VocabWordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vocab-list': {
      id: '/vocab-list'
      path: '/vocab-list'
      fullPath: '/vocab-list'
      preLoaderRoute: typeof VocabListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/release-notes': {
      id: '/release-notes'
      path: '/release-notes'
      fullPath: '/release-notes'
      preLoaderRoute: typeof ReleaseNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanji-list': {
      id: '/kanji-list'
      path: '/kanji-list'
      fullPath: '/kanji-list'
      preLoaderRoute: typeof KanjiListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kana-write-quiz': {
      id: '/kana-write-quiz'
      path: '/kana-write-quiz'
      fullPath: '/kana-write-quiz'
      preLoaderRoute: typeof KanaWriteQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kana-write': {
      id: '/kana-write'
      path: '/kana-write'
      fullPath: '/kana-write'
      preLoaderRoute: typeof KanaWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kana-reference': {
      id: '/kana-reference'
      path: '/kana-reference'
      fullPath: '/kana-reference'
      preLoaderRoute: typeof KanaReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kana-quiz': {
      id: '/kana-quiz'
      path: '/kana-quiz'
      fullPath: '/kana-quiz'
      preLoaderRoute: typeof KanaQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draw-search': {
      id: '/draw-search'
      path: '/draw-search'
      fullPath: '/draw-search'
      preLoaderRoute: typeof DrawSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draw': {
      id: '/draw'
      path: '/draw'
      fullPath: '/draw'
      preLoaderRoute: typeof DrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocab/$word': {
      id: '/vocab/$word'
      path: '/vocab/$word'
      fullPath: '/vocab/$word'
      preLoaderRoute: typeof VocabWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanji/$char': {
      id: '/kanji/$char'
      path: '/kanji/$char'
      fullPath: '/kanji/$char'
      preLoaderRoute: typeof KanjiCharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kana/$char': {
      id: '/kana/$char'
      path: '/kana/$char'
      fullPath: '/kana/$char'
      preLoaderRoute: typeof KanaCharRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreditsRoute: CreditsRoute,
  DrawRoute: DrawRoute,
  DrawSearchRoute: DrawSearchRoute,
  HistoryRoute: HistoryRoute,
  KanaQuizRoute: KanaQuizRoute,
  KanaReferenceRoute: KanaReferenceRoute,
  KanaWriteRoute: KanaWriteRoute,
  KanaWriteQuizRoute: KanaWriteQuizRoute,
  KanjiListRoute: KanjiListRoute,
  ProfileRoute: ProfileRoute,
  QuizRoute: QuizRoute,
  ReleaseNotesRoute: ReleaseNotesRoute,
  ReviewRoute: ReviewRoute,
  ShareRoute: ShareRoute,
  VocabListRoute: VocabListRoute,
  KanaCharRoute: KanaCharRoute,
  KanjiCharRoute: KanjiCharRoute,
  VocabWordRoute: VocabWordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
