import rawKanjiData from "./raw-kanji-data.json"
import idN5 from "./i18n/kanji-id-N5.json"
import idN4 from "./i18n/kanji-id-N4.json"
import idN3 from "./i18n/kanji-id-N3.json"
import idN2 from "./i18n/kanji-id-N2.json"
import idN1 from "./i18n/kanji-id-N1.json"
import type { Locale } from "@/lib/progress/store"

export interface KanjiExample {
  kana: string
  /** English translation. Always present. */
  translation: string
  /** Indonesian translation. Optional — falls back to English when missing. */
  translationId?: string
  KanaRomaji: string
}

export interface Kanji {
  kanji: string
  /** English meanings. Always present. */
  meaning: string[]
  /** Indonesian meanings. Optional, may have a different array length than
   *  `meaning` if the translator collapsed alternates. Falls back to `meaning`
   *  (English) when missing or empty. */
  meaningId?: string[]
  romaji: string
  onReading: string
  kunReading: string
  onReadingRomaji: string
  kunReadingRomaji: string
  examples: KanjiExample[]
  jlptLevel: string
}

interface KanjiData {
  [key: string]: Kanji[]
}

interface KanjiIdSidecarEntry {
  meaningId?: string[]
  examplesId?: { kana: string; translationId: string }[]
}

type KanjiIdSidecar = Record<string, KanjiIdSidecarEntry>

// Per-level Indonesian sidecars merged into a single lookup keyed by kanji
// char. Each sidecar JSON is generated by a translation step and committed.
// Missing entries silently fall back to English at read time.
const idSidecar: KanjiIdSidecar = {
  ...(idN5 as KanjiIdSidecar),
  ...(idN4 as KanjiIdSidecar),
  ...(idN3 as KanjiIdSidecar),
  ...(idN2 as KanjiIdSidecar),
  ...(idN1 as KanjiIdSidecar),
}

const transformKanjiData = (data: any[]): KanjiData => {
  const transformedData: KanjiData = {}

  data.forEach((item) => {
    const level = item.JLPTLevel
    if (!transformedData[level]) {
      transformedData[level] = []
    }

    const idEntry = idSidecar[item.Kanji]
    const idExamplesByKana = new Map<string, string>()
    for (const ex of idEntry?.examplesId ?? []) {
      idExamplesByKana.set(ex.kana, ex.translationId)
    }

    const examples: KanjiExample[] = (item.Examples || []).map((ex: any) => {
      const translationId = idExamplesByKana.get(ex.kana)
      return {
        kana: ex.kana,
        translation: ex.translation,
        ...(translationId ? { translationId } : {}),
        KanaRomaji: ex.KanaRomaji,
      }
    })

    transformedData[level].push({
      kanji: item.Kanji,
      meaning: item.Meaning,
      ...(idEntry?.meaningId && idEntry.meaningId.length > 0
        ? { meaningId: idEntry.meaningId }
        : {}),
      romaji: item.OnReadingRomaji, // For backward compatibility
      onReading: item.OnReading,
      kunReading: item.KunReading,
      onReadingRomaji: item.OnReadingRomaji,
      kunReadingRomaji: item.KunReadingRomaji,
      examples,
      jlptLevel: item.JLPTLevel,
    })
  })

  return transformedData
}

export const kanjiData: KanjiData = transformKanjiData(rawKanjiData)

/** Get meanings for a kanji in the active locale, falling back to English when
 *  Indonesian isn't available. Always returns a non-empty array. */
export function getKanjiMeaning(kanji: Kanji, locale: Locale): string[] {
  if (locale === "id" && kanji.meaningId && kanji.meaningId.length > 0) {
    return kanji.meaningId
  }
  return kanji.meaning
}

/** Get example translation in active locale, falling back to English. */
export function getExampleTranslation(ex: KanjiExample, locale: Locale): string {
  if (locale === "id" && ex.translationId) return ex.translationId
  return ex.translation
}
